# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fastnn.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x66\x61stnn.proto\x12\x06\x66\x61stnn\"0\n\rCreateRequest\x12\t\n\x01x\x18\x01 \x03(\x02\x12\t\n\x01y\x18\x02 \x03(\x02\x12\t\n\x01z\x18\x03 \x03(\x02\"\x1c\n\x0e\x43reateResponse\x12\n\n\x02id\x18\x01 \x01(\t\"\x1c\n\x0e\x44\x65stroyRequest\x12\n\n\x02id\x18\x01 \x01(\t\"\x11\n\x0f\x44\x65stroyResponse\"F\n\x0cQueryRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\t\n\x01x\x18\x02 \x03(\x02\x12\t\n\x01y\x18\x03 \x03(\x02\x12\t\n\x01z\x18\x04 \x03(\x02\x12\t\n\x01k\x18\x05 \x01(\x05\"3\n\rQueryResponse\x12\x0f\n\x07indices\x18\x01 \x03(\x05\x12\x11\n\tdistances\x18\x02 \x03(\x02\x32\xba\x01\n\rFastNnService\x12\x37\n\x06\x43reate\x12\x15.fastnn.CreateRequest\x1a\x16.fastnn.CreateResponse\x12:\n\x07\x44\x65stroy\x12\x16.fastnn.DestroyRequest\x1a\x17.fastnn.DestroyResponse\x12\x34\n\x05Query\x12\x14.fastnn.QueryRequest\x1a\x15.fastnn.QueryResponseB\t\xaa\x02\x06\x46\x61stNnb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fastnn_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\006FastNn'
  _globals['_CREATEREQUEST']._serialized_start=24
  _globals['_CREATEREQUEST']._serialized_end=72
  _globals['_CREATERESPONSE']._serialized_start=74
  _globals['_CREATERESPONSE']._serialized_end=102
  _globals['_DESTROYREQUEST']._serialized_start=104
  _globals['_DESTROYREQUEST']._serialized_end=132
  _globals['_DESTROYRESPONSE']._serialized_start=134
  _globals['_DESTROYRESPONSE']._serialized_end=151
  _globals['_QUERYREQUEST']._serialized_start=153
  _globals['_QUERYREQUEST']._serialized_end=223
  _globals['_QUERYRESPONSE']._serialized_start=225
  _globals['_QUERYRESPONSE']._serialized_end=276
  _globals['_FASTNNSERVICE']._serialized_start=279
  _globals['_FASTNNSERVICE']._serialized_end=465
# @@protoc_insertion_point(module_scope)
