# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import fastnn_pb2 as fastnn__pb2 # import fastnn_pb2 as fastnn__pb2


class FastNnServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Create = channel.unary_unary(
                '/fastnn.FastNnService/Create',
                request_serializer=fastnn__pb2.CreateRequest.SerializeToString,
                response_deserializer=fastnn__pb2.CreateResponse.FromString,
                )
        self.Destroy = channel.unary_unary(
                '/fastnn.FastNnService/Destroy',
                request_serializer=fastnn__pb2.DestroyRequest.SerializeToString,
                response_deserializer=fastnn__pb2.DestroyResponse.FromString,
                )
        self.Query = channel.unary_unary(
                '/fastnn.FastNnService/Query',
                request_serializer=fastnn__pb2.QueryRequest.SerializeToString,
                response_deserializer=fastnn__pb2.QueryResponse.FromString,
                )


class FastNnServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Destroy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Query(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FastNnServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=fastnn__pb2.CreateRequest.FromString,
                    response_serializer=fastnn__pb2.CreateResponse.SerializeToString,
            ),
            'Destroy': grpc.unary_unary_rpc_method_handler(
                    servicer.Destroy,
                    request_deserializer=fastnn__pb2.DestroyRequest.FromString,
                    response_serializer=fastnn__pb2.DestroyResponse.SerializeToString,
            ),
            'Query': grpc.unary_unary_rpc_method_handler(
                    servicer.Query,
                    request_deserializer=fastnn__pb2.QueryRequest.FromString,
                    response_serializer=fastnn__pb2.QueryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fastnn.FastNnService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FastNnService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/fastnn.FastNnService/Create',
            fastnn__pb2.CreateRequest.SerializeToString,
            fastnn__pb2.CreateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Destroy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/fastnn.FastNnService/Destroy',
            fastnn__pb2.DestroyRequest.SerializeToString,
            fastnn__pb2.DestroyResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Query(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/fastnn.FastNnService/Query',
            fastnn__pb2.QueryRequest.SerializeToString,
            fastnn__pb2.QueryResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
